sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: T5hyBcrrYb4yTsWWV1sQBBVweLwxvMFkqOepZdIXHHRh5dJ21l28ahFpFgUShZ5BDXJ4SV1dn0fEzh+Jl4DwRz1FLVIoatEYQA1gXb+CqQ8wJ5hT6QkLQKNBwLYxMUy9zO5KizTsrKEe4JtEkmyBZ88xsj/r2Z0d06RZdnNMRS5b4x5FwGLxThN2VG/BLMz1OEq0vJWamLjeuCXIXlXD7nn+yHc5ZV5ftov+mRoRbezvmA4uEpPkq01C9AuGGA76W2HfT+QrJmPnZ69xvTmNtNq3nuNPMAdR8ufUPDAmq9/OGslFtQ/v5P462P/DfnOVZNpcnaTL3ftXMoryX9u7FrjNA2i5Z+j5cl7M58jB78o9mwyWdP5j2QmzciOUH/vg5AUobwENrYVzq4OfyKhEihpUn7eU//c/dmhtK2OOYNOAiHgysLRbAwLFV7kSly43hgAmIBgSiV3AeCrvQoKmswScDO4y5jN/CrhjG1jugyXmqEqt0gGKIki+hR3jW19s/hNICspxmOV1w21H2wvrfYa14C8f62DZZRkuwZXJQwdj2FdCdlH3UI39hHpfOtpPvlminGHYXq/ZUIJZ23SqIpVsEK2W1fsNGLwx3lwBe5SUzlZW/vuHNb9Dhz9sZhH1aejS9yEvP2dnZLqIuSd5lcBTbLUYZFAAeVYP9ZBOhdg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Walter-Sherwood-s-Probation_5993
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy